In [3]:
#numpy--------------------------------task1----------------------------------

import numpy as np

## 1. Creating Arrays ##

# 1D array with integers 1-10
array_1d = np.arange(1, 11)

# 2D array (3x3) with integers 1-9
array_2d = np.arange(1, 10).reshape(3, 3)

# 3D array (3x5x3) with random floats between 0 and 1
array_3d = np.random.rand(3, 5, 3)

## 2. Displaying Array Properties ##

def display(arr, name):
    print(f"\n{name} Properties:")
    print("Array:")
    print(arr)
    print(f"Shape: {arr.shape}")
    print(f"Size: {arr.size}")
    print(f"Data type: {arr.dtype}")

# Display properties for each array
display(array_1d, "1D Array")
display(array_2d, "2D Array")
display(array_3d, "3D Array")


1D Array Properties:
Array:
[ 1  2  3  4  5  6  7  8  9 10]
Shape: (10,)
Size: 10
Data type: int32

2D Array Properties:
Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Size: 9
Data type: int32

3D Array Properties:
Array:
[[[0.91894578 0.71030783 0.3188351 ]
  [0.36767139 0.10541933 0.24970126]
  [0.54942002 0.28825478 0.52980427]
  [0.72049701 0.33401305 0.36544698]
  [0.25146545 0.60219744 0.16230742]]

 [[0.21952443 0.02589182 0.52610706]
  [0.64477977 0.04291888 0.05944038]
  [0.02847928 0.86301367 0.44127625]
  [0.96591692 0.40166176 0.27810212]
  [0.571898   0.10664841 0.64689947]]

 [[0.74170967 0.16016623 0.33252934]
  [0.38328015 0.50128429 0.05544586]
  [0.47677894 0.11296467 0.90274705]
  [0.16957552 0.24746599 0.58140445]
  [0.88970483 0.51787443 0.31284079]]]
Shape: (3, 5, 3)
Size: 45
Data type: float64


In [4]:
# TASK2---------------------------------------------------------

# 1. Create array from list
data = [10, 20, 30, 40, 50, 60, 70, 80, 90]
arr = np.array(data)

# 2. Perform operations
first_three = arr[:3]  # First three elements
alternate = arr[::2]  # Every alternate element
reversed_arr = arr[::-1]  # Reversed array

# Display results

print("\nOriginal array:", arr)
print("First three elements:", first_three)
print("Every alternate element:", alternate)
print("Reversed array:", reversed_arr)


Original array: [10 20 30 40 50 60 70 80 90]
First three elements: [10 20 30]
Every alternate element: [10 30 50 70 90]
Reversed array: [90 80 70 60 50 40 30 20 10]


In [5]:
# TASK3------------------------------------------
import numpy as np

# Step 1: Create two NumPy arrays with 5 random integers between 1 and 20
A = np.random.randint(1, 21, size=5)
B = np.random.randint(1, 21, size=5)

print("Array A:", A)
print("Array B:", B)

# Step 2a: Element-wise operations
print("\nElement-wise Addition:      ", A + B)
print("Element-wise Subtraction:   ", A - B)
print("Element-wise Multiplication:", A * B)
print("Element-wise Division:      ", A / B)

# Step 2b: Dot product
print("\nDot Product of A and B:     ", np.dot(A, B))

# Step 2c: Statistics on array A
print("\nMean of A:                  ", np.mean(A))
print("Median of A:                ", np.median(A))
print("Standard Deviation of A:    ", np.std(A))
print("Variance of A:              ", np.var(A))

# Step 2d: Max/Min of array B and their indices
print("\nMaximum of B:               ", np.max(B))
print("Index of Maximum in B:      ", np.argmax(B))
print("Minimum of B:               ", np.min(B))
print("Index of Minimum in B:      ", np.argmin(B))


Array A: [ 9  8 17 15 11]
Array B: [18 16  4  6  5]

Element-wise Addition:       [27 24 21 21 16]
Element-wise Subtraction:    [-9 -8 13  9  6]
Element-wise Multiplication: [162 128  68  90  55]
Element-wise Division:       [0.5  0.5  4.25 2.5  2.2 ]

Dot Product of A and B:      503

Mean of A:                   12.0
Median of A:                 11.0
Standard Deviation of A:     3.4641016151377544
Variance of A:               12.0

Maximum of B:                18
Index of Maximum in B:       0
Minimum of B:                4
Index of Minimum in B:       2


In [6]:
# TASK4------------------------------------------------------------------------
import numpy as np

# Step 1: Create a 1D array with integers from 1 to 12
arr = np.arange(1, 13)
print("Original 1D Array:")
print(arr)


arr2d = arr.reshape(4, 3)
print("\nReshaped to 2D (4, 3):")
print(arr2d)

# Step 2b: Reshape into 3D array of shape (2, 2, 3)
arr3d = arr.reshape(2, 2, 3)
print("\nReshaped to 3D (2, 2, 3):")
print(arr3d)

# Step 2c: Transpose the 2D array and display its shape
arr2dt = arr2d.T
print("\nTransposed 2D Array:")
print(arr2dt)
print("Shape after transpose:", arr2dt.shape)


Original 1D Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped to 2D (4, 3):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Reshaped to 3D (2, 2, 3):
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Transposed 2D Array:
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
Shape after transpose: (3, 4)


In [7]:
# TASK 5--------------------------------------------------

import numpy as np

# Step 1: Create array with 15 random numbers from 10 to 50
a = np.random.randint(10, 51, size=15)
print("Original array:", a)

# Step 2a: Elements greater than 25
gt25 = a[a > 25]
print("Greater than 25:", gt25)

# Step 2b: Replace elements less than 30 with 0
a_mod = a.copy()
a_mod[a_mod < 30] = 0
print("After replacing <30 with 0:", a_mod)

# Step 2c: Count elements divisible by 5
count5 = np.sum(a % 5 == 0)
print("Count divisible by 5:", count5)


Original array: [27 26 35 35 29 23 27 31 18 12 19 26 19 47 27]
Greater than 25: [27 26 35 35 29 27 31 26 47 27]
After replacing <30 with 0: [ 0  0 35 35  0  0  0 31  0  0  0  0  0 47  0]
Count divisible by 5: 2


In [8]:
# TASK6-----------------------------
import numpy as np

# 1. Create an array of 10 equally spaced values between 0 and 1
arr1 = np.linspace(0, 1, 10)
print("Equally spaced values from 0 to 1:", arr1)

# 2. Create an identity matrix of size 4x4
identity = np.eye(4)
print("\nIdentity matrix 4x4:\n", identity)

# 3. Generate a 1D array of 20 random integers between 1 and 100
arr2 = np.random.randint(1, 101, size=20)
print("\nOriginal array:", arr2)

# Sort the array
sorted = np.sort(arr2)
print("Sorted array:", sorted)

# Get the 5 largest elements
largest5 = sorted[-5:]
print("5 largest elements:", largest5)


Equally spaced values from 0 to 1: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]

Identity matrix 4x4:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Original array: [97 12 28 80 60 13 40 70 68 70 68 41 51 27 17 72 62 65 35 11]
Sorted array: [11 12 13 17 27 28 35 40 41 51 60 62 65 68 68 70 70 72 80 97]
5 largest elements: [70 70 72 80 97]


In [9]:
# TASK7-----------------------------------------------------
import numpy as np
import time

# Step 1: Generate two large random arrays of size (100, 100)
A = np.random.rand(100, 100)
B = np.random.rand(100, 100)

# Step 2: Measure time before multiplication
start = time.time()

# Step 3: Perform matrix multiplication
C = np.dot(A, B)

# Step 4: Try to compute determinant and inverse (if possible)
try:
    det = np.linalg.det(C)
    inv = np.linalg.inv(C)
    det_status = "Determinant computed"
    inv_status = "Inverse computed"

    
except np.linalg.LinAlgError:
    det = None
    inv = None
    det_status = "Determinant not computable"
    inv_status = "Matrix is singular; inverse not possible"

# Step 5: Measure time after all operations
end = time.time()
elapsed = end - start

# Step 6: Output results
print("Matrix multiplication completed.")
print(det_status)
print(inv_status)
print("Time taken: {:.4f} seconds".format(elapsed))

# Optional: print determinant value (rounded)
if det is not None:
    print("Determinant: {:.4f}".format(det))


Matrix multiplication completed.
Determinant computed
Inverse computed
Time taken: 0.1363 seconds
Determinant: 565892355322394816583668976602171824195937968848896.0000
